const STORE_DATA = "STORE_DATA";
const INVALID_TYPE_OF_DATA = "INVALID_TYPE_OF_DATA";

const SEARCH_IMAGES = "SEARCH_IMAGES";
const LOAD_MORE_IMAGES = "LOAD_MORE_IMAGES";

export {
  SEARCH_IMAGES,
  LOAD_MORE_IMAGES, 
  STORE_DATA, 
  INVALID_TYPE_OF_DATA 
};